spring.application.name=analytics-api

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/analytics}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

security.jwt.secret=${JWT_SECRET:change-this-secret-change-this-secret}
security.jwt.expiration=${JWT_EXPIRATION:3600}